-- CRIAR NO JAVADB O BANCO DE DADOS agendabd (NOME EM LETRAS MINÚSCULAS)
-- E O USUÁRIO app E SENHA app (TAMBÉM TUDO COM LETRAS MINÚSCULAS)

CREATE TABLE TB_CONTATO (
  ID_CONTATO BIGINT  NOT NULL GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1) CONSTRAINT PK_CONTATO PRIMARY KEY,
  NM_CONTATO VARCHAR(100) NOT NULL,
  DT_NASCIMENTO DATE NOT NULL,
  VL_TELEFONE VARCHAR(16),
  VL_EMAIL VARCHAR(100),
  DT_CADASTRO TIMESTAMP NOT NULL
);